version: '3'
services:
  tdengine:
    image: tdengine/tdengine:3.0.0.1
    container_name: tdengine
    hostname: tdengine
    ports:
    - 6030:6030
    - 6035:6035
    - 6041:6041
    - 6030-6040:6030-6040/udp
    volumes:
    - ./data/lib:/var/lib/taos:Z
    - ./data/log:/var/log/taos:Z
    environment:
      TZ: Asia/Shanghai
    restart: always
    tty: true
